image: python:3.12-slim
tasks:
  - name: run
    init: |
      python -m pip install -U pip
      pip install -r requirements.txt
    command: |
      export HOST=0.0.0.0
      python app.py
ports:
  - port: 5000
    onOpen: open-browser
    visibility: public
